
let lastRequest=null;let lastResult=null;
const PAGE_SIZE_DEFAULT=100;
const tableState={mail:{page:1,pageSize:PAGE_SIZE_DEFAULT,search:""},ebill:{page:1,pageSize:PAGE_SIZE_DEFAULT,search:""},bpay:{page:1,pageSize:PAGE_SIZE_DEFAULT,search:""},suppressed:{page:1,pageSize:PAGE_SIZE_DEFAULT,search:""}};
const baseCols=["subscriptionNumber","mastheadName","billingName","billingAddressLine1","billingAddressLine2","deliveryAddressLine1","deliveryAddressLine2","ratesCode","invoiceDate","paidToDate","bPayReferenceNumber","balanceOwing","balanceOwingGST","rateOption1Period","rateOption1Cost","rateOption1GST","rateOption2Period","rateOption2Cost","rateOption2GST","rateOption3Period","rateOption3Cost","rateOption3GST","officeAddress","cashInstructions","chequeInstructions","creditCardInstructions","email","renewalDeliveryMethod","publicationName","subscriptionStatus","routeId","pdfGeneratorTemplateId","pdfTemplateStatus","pdfRuleId","templateSelectionReason","documentType","hasBalanceOwing","hasOnlineStartCode","validRateCount","suppressionReason","suppressionRuleId"];
function colsFor(key,mode){const cols=[...baseCols];if(mode==="live"&&key==="mail")cols.push("mailPdf");if(mode==="live"&&key==="ebill")cols.push("ebillPdfUrl");return cols}
function allSearchCols(mode){return Array.from(new Set([...baseCols,"mailPdf","ebillPdfUrl"]))}
function todayPlus(days){const d=new Date();d.setDate(d.getDate()+days);return d.toISOString().slice(0,10)}
function esc(v){return String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]))}
function setBusy(v){document.getElementById("busy").classList.toggle("d-none",!v);document.getElementById("dryRunBtn").disabled=v;document.getElementById("liveRunBtn").disabled=v||!lastResult||Number(lastResult.missing_bpay_count||0)>0;document.getElementById("resetBtn").disabled=v}
function alert(type,msg){document.getElementById("alertBox").innerHTML=`<div class="alert alert-${type}">${msg}</div>`}
function clearAlert(){document.getElementById("alertBox").innerHTML=""}
function validateInclude(){const mail=document.getElementById("includeMail").checked;const ebill=document.getElementById("includeEbill").checked;if(!mail&&!ebill){alert("warning","Select Mail, eBill, or both before running.");return false}return true}
async function api(path,body){const r=await fetch(`/api${path}`,{method:"POST",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});if(r.status===401||r.status===403){window.location.href="/login?returnTo="+encodeURIComponent(window.location.pathname+window.location.search);return null}const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data?.detail||data?.error||`Request failed (${r.status})`);return data}
function metric(title,value,variant="primary",icon=""){return `<div class="col-sm-6 col-xl-3"><div class="card card-metric border-${variant}"><div class="card-body d-flex justify-content-between gap-3"><div><div class="${variant==='danger'?'text-danger':'text-muted'}">${esc(title)}</div><div class="display-6">${esc(value)}</div><div class="small">candidates</div></div>${icon?`<div class="metric-icon text-${variant}">${icon}</div>`:""}</div></div></div>`}
function getRows(result,names){for(const name of names){const value=name.split('.').reduce((o,k)=>o?.[k],result);if(Array.isArray(value))return value}return []}
function responseOf(result){return result?.response||result||{}}
function countOf(result,key,rows){const r=responseOf(result);const direct=Number(r?.[key]);if(Number.isFinite(direct))return direct;const nested=Number(result?.[key]);if(Number.isFinite(nested))return nested;return Array.isArray(rows)?rows.length:0}
function downloadsOf(result){return responseOf(result).downloads||result?.downloads||{}}
function warningsOf(result){return responseOf(result).warnings||result?.warnings||[]}
function getDataSets(result){return{mail:getRows(result,["mail_rows","mail_renewals","mail_candidates","mail_preview","preview.mail","rows.mail","mail"]),ebill:getRows(result,["ebill_rows","ebill_renewals","ebill_candidates","ebill_preview","preview.ebill","rows.ebill","ebill"]),bpay:getRows(result,["missing_bpay_rows","missing_bpay","missing_bpay_candidates","missing_bpay_preview","preview.missing_bpay","rows.missing_bpay"]),suppressed:getRows(result,["suppressed_rows","suppressed","suppressed_candidates","suppressed_preview","preview.suppressed","rows.suppressed"])}}
function renderSummary(result){const rows=getDataSets(result);const r=responseOf(result);const mode=r?.mode||result?.mode||"dry_run";const isDry=mode!=="live";const missing=countOf(result,"missing_bpay_count",rows.bpay);document.getElementById("summary").classList.remove("d-none");document.getElementById("summary").innerHTML=[metric("Mail",countOf(result,"mail_count",rows.mail),"primary","✉"),metric("eBill",countOf(result,"ebill_count",rows.ebill),"primary","▣"),metric("Missing BPAY",missing,missing>0?"danger":"success",missing>0?"!":"✓"),metric("Suppressed",countOf(result,"suppressed_count",rows.suppressed),"secondary","●")].join("");const warnings=warningsOf(result).map(w=>`<div class="alert alert-warning mb-2">${esc(w)}</div>`).join("");document.getElementById("alertBox").innerHTML=warnings;document.getElementById("liveRunBtn").disabled=missing>0;document.getElementById("dryRunBadge").classList.toggle("d-none",!isDry);document.getElementById("dryRunFootnote").classList.toggle("d-none",!isDry)}
function downloadLabel(key){if(key==="mail_csv")return "Mail CSV";if(key==="ebill_csv")return "eBill CSV";if(key==="missing_bpay_csv")return "Missing BPAY CSV";if(key==="suppressed_csv")return "Suppressed CSV";if(key==="all_candidates_csv")return "All candidates CSV";if(key==="generated_manifest")return "Generated manifest";if(key.startsWith("mail_pdf_"))return `Mail PDF ${key.replace("mail_pdf_","")}`;if(key.startsWith("ebill_pdf_"))return `eBill PDF ${key.replace("ebill_pdf_","")}`;return key}
function renderDownloads(downloads,mode="dry_run"){const isLive=mode==="live";const links=Object.entries(downloads||{}).map(([k,u])=>`<a class="btn btn-outline-${isLive&&k.includes("pdf")?"success":"primary"} btn-sm me-2 mb-2" href="${esc(u)}" target="_blank" rel="noopener">${esc(downloadLabel(k))}</a>`).join("");document.getElementById("downloads").classList.remove("d-none");document.getElementById("downloads").innerHTML=`<div class="card"><div class="card-body"><div class="d-flex justify-content-between flex-wrap gap-2"><h5 class="mb-2">Downloads (${isLive?"live run":"dry run"})</h5><span class="text-muted small">${isLive?"Generated PDFs and reports from the live run":"CSV files contain the generated candidate lists"}</span></div>${links||"<span class='text-muted'>No downloads available.</span>"}</div></div>`}
function filterRows(rows,search,mode="dry_run"){if(!search)return rows;const q=search.toLowerCase();const searchCols=allSearchCols(mode);return rows.filter(r=>searchCols.some(c=>String(r?.[c]??"").toLowerCase().includes(q)))}
function renderCell(row,col){const value=row?.[col];if(col==="ebillPdfUrl"&&value){return `<a class="pdf-link" href="${esc(value)}" target="_blank" rel="noopener">Open PDF</a>`}return esc(value)}
function renderTable(key,elId,title,rows,total,mode="dry_run"){const el=document.getElementById(elId);const state=tableState[key];const tableCols=colsFor(key,mode);const filtered=filterRows(rows||[],state.search,mode);const totalRows=typeof total==='number'?total:(rows||[]).length;const pageCount=Math.max(1,Math.ceil(filtered.length/state.pageSize));state.page=Math.min(Math.max(1,state.page),pageCount);const start=(state.page-1)*state.pageSize;const pageRows=filtered.slice(start,start+state.pageSize);const badge=mode==="live"?"":` <span class="badge text-bg-warning ms-2">DRY RUN</span>`;if(!rows||rows.length===0){el.innerHTML=`<div class="card"><div class="card-body"><h5>${esc(title)}${badge}</h5><p class="text-muted mb-0">No rows.</p></div></div>`;return}const body=pageRows.map(r=>`<tr>${tableCols.map(h=>`<td>${renderCell(r,h)}</td>`).join("")}</tr>`).join("");const showingFrom=filtered.length?start+1:0;const showingTo=Math.min(start+state.pageSize,filtered.length);el.innerHTML=`<div class="card"><div class="card-body"><div class="d-flex justify-content-between align-items-start flex-wrap gap-3 mb-3"><div><h5 class="mb-1">${esc(title)}${badge}</h5><div class="text-muted small">Showing ${showingFrom} to ${showingTo} of ${filtered.length} results${totalRows!==filtered.length?` (${totalRows} total candidates)`:""}.</div></div><div class="d-flex gap-2 flex-wrap"><input class="form-control form-control-sm" style="max-width:260px" placeholder="Search…" value="${esc(state.search)}" oninput="updateSearch('${key}', this.value)"><button class="btn btn-outline-primary btn-sm" onclick="exportVisible('${key}')">Export this table</button><select class="form-select form-select-sm" style="width:90px" onchange="updatePageSize('${key}', this.value)"><option value="100" ${state.pageSize==100?'selected':''}>100</option><option value="250" ${state.pageSize==250?'selected':''}>250</option><option value="500" ${state.pageSize==500?'selected':''}>500</option></select></div></div><div class="table-wrap"><table class="table table-sm table-striped small-table wide-table"><thead><tr>${tableCols.map(h=>`<th>${esc(h)}</th>`).join("")}</tr></thead><tbody>${body}</tbody></table></div><div class="table-footer mt-3"><span class="text-muted small">Rows per page: ${state.pageSize}</span><div class="btn-group btn-group-sm"><button class="btn btn-outline-secondary" ${state.page<=1?'disabled':''} onclick="goPage('${key}',1)">«</button><button class="btn btn-outline-secondary" ${state.page<=1?'disabled':''} onclick="goPage('${key}',${state.page-1})">‹</button><span class="btn btn-primary disabled">${state.page}</span><button class="btn btn-outline-secondary" ${state.page>=pageCount?'disabled':''} onclick="goPage('${key}',${state.page+1})">›</button><button class="btn btn-outline-secondary" ${state.page>=pageCount?'disabled':''} onclick="goPage('${key}',${pageCount})">»</button></div></div></div></div>`}
function updateTabs(result){const rows=getDataSets(result);const mail=countOf(result,"mail_count",rows.mail);const ebill=countOf(result,"ebill_count",rows.ebill);const bpay=countOf(result,"missing_bpay_count",rows.bpay);const suppressed=countOf(result,"suppressed_count",rows.suppressed);document.getElementById("mailTab").textContent=`Mail renewals (${mail})`;document.getElementById("ebillTab").textContent=`eBill renewals (${ebill})`;document.getElementById("bpayTab").textContent=`Missing BPAY (${bpay})`;document.getElementById("suppressedTab").textContent=`Suppressed preview (${suppressed})`;document.getElementById("bpayTab").classList.toggle("text-danger",Number(bpay||0)>0)}
function renderResults(result){const r=responseOf(result);const mode=r?.mode||result?.mode||"dry_run";document.getElementById("resultTabs").classList.remove("d-none");renderSummary(result);renderDownloads(downloadsOf(result),mode);updateTabs(result);const rows=getDataSets(result);renderTable("mail","mailTable",mode==="live"?"Mail renewals":"Mail renewals (dry run preview)",rows.mail,countOf(result,"mail_count",rows.mail),mode);renderTable("ebill","ebillTable",mode==="live"?"eBill renewals":"eBill renewals (dry run preview)",rows.ebill,countOf(result,"ebill_count",rows.ebill),mode);renderTable("bpay","bpayTable",mode==="live"?"Missing BPAY":"Missing BPAY (dry run preview)",rows.bpay,countOf(result,"missing_bpay_count",rows.bpay),mode);if((r?.suppressed_included??result?.suppressed_included)===false){document.getElementById("suppressedTable").innerHTML=`<div class="card"><div class="card-body"><h5>Suppressed preview</h5><p class="text-muted mb-0">Suppressed CSV/table output was not generated for this run. Tick <strong>Suppressed</strong> before running a dry run to include those rows.</p></div></div>`}else{renderTable("suppressed","suppressedTable",mode==="live"?"Suppressed":"Suppressed preview (dry run)",rows.suppressed,countOf(result,"suppressed_count",rows.suppressed),mode)}}
function rerender(){if(lastResult)renderResults(lastResult)}
function updateSearch(key,value){tableState[key].search=value;tableState[key].page=1;rerender()}
function updatePageSize(key,value){tableState[key].pageSize=Number(value)||PAGE_SIZE_DEFAULT;tableState[key].page=1;rerender()}
function goPage(key,page){tableState[key].page=page;rerender()}
function exportVisible(key){if(!lastResult)return;const mode=responseOf(lastResult)?.mode||lastResult?.mode||"dry_run";const tableCols=colsFor(key,mode);const rows=filterRows(getDataSets(lastResult)[key]||[],tableState[key].search,mode);const csv=[tableCols.join(",")].concat(rows.map(r=>tableCols.map(c=>`"${String(r[c]??"").replace(/"/g,'""')}"`).join(","))).join("\n");const blob=new Blob([csv],{type:"text/csv;charset=utf-8"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=`${key}-${mode==="live"?"live-run":"dry-run-preview"}.csv`;a.click();URL.revokeObjectURL(url)}
async function loadUser(){const r=await fetch("/auth/me",{cache:"no-store",credentials:"include"});const data=await r.json();if(!data.authenticated){window.location.href="/login?returnTo="+encodeURIComponent(window.location.pathname);return}document.getElementById("userLabel").textContent=data.email}
function parseList(value){return String(value||"").split(/[\n,]+/).map(v=>v.trim()).filter(Boolean)}
function parseIntList(value){return parseList(value).map(v=>Number(v)).filter(v=>Number.isFinite(v))}
function buildRequest(){return{invoice_date:document.getElementById("invoiceDate").value,max_days_to_renewal_at_invoice_date:Number(document.getElementById("renewalDays").value||14),max_days_in_grace_at_invoice_date:Number(document.getElementById("graceDays").value||28),include_mail:document.getElementById("includeMail").checked,include_ebill:document.getElementById("includeEbill").checked,include_suppressed:document.getElementById("includeSuppressed").checked,suppress_subscription_ids:parseIntList(document.getElementById("suppressSubscriptionIds").value),suppress_route_ids:parseList(document.getElementById("suppressRouteIds").value)}}
document.getElementById("invoiceDate").value=todayPlus(1);
document.getElementById("dryRunForm").addEventListener("submit",async(e)=>{e.preventDefault();clearAlert();if(!validateInclude())return;lastRequest=buildRequest();try{setBusy(true);const result=await api("/renewals/dry-run/details",lastRequest);if(!result)return;lastResult=result;Object.values(tableState).forEach(s=>{s.page=1;s.pageSize=PAGE_SIZE_DEFAULT});renderResults(result)}catch(err){alert("danger",esc(err.message))}finally{setBusy(false)}});
document.getElementById("liveRunBtn").addEventListener("click",async()=>{if(!lastRequest)return;if(!confirm("Prepare renewal communications for this invoice date? Mail PDFs may be generated and eBill records may be prepared according to the selected options."))return;try{setBusy(true);const result=await api("/renewals/run",lastRequest);alert(result.status==="blocked_missing_bpay"?"danger":"success",`Run status: <span class="mono">${esc(result.status)}</span>. Run ID: <span class="mono">${esc(result.run_id)}</span>`);lastResult=result;Object.values(tableState).forEach(s=>{s.page=1;s.pageSize=PAGE_SIZE_DEFAULT});renderResults(result)}catch(err){alert("danger",esc(err.message))}finally{setBusy(false)}});
document.getElementById("resetBtn").addEventListener("click",()=>{lastRequest=null;lastResult=null;clearAlert();document.getElementById("summary").classList.add("d-none");document.getElementById("downloads").classList.add("d-none");document.getElementById("resultTabs").classList.add("d-none");document.getElementById("dryRunBadge").classList.add("d-none");document.getElementById("dryRunFootnote").classList.add("d-none");["mailTable","ebillTable","bpayTable","suppressedTable"].forEach(id=>document.getElementById(id).innerHTML="");setBusy(false)});
document.getElementById("logoutBtn").addEventListener("click",async()=>{await fetch("/auth/logout",{method:"POST",credentials:"include"});window.location.href="/login"});
loadUser();
